### ISSUE TITLE
Permission Request 

### ISSUE THREAD

**Issue by zths** [emerladCoder/RPG-Maker-MV-Cheat-Menu-Plugin#2]
@emerladCoder 
Hello
I have including this repo‘s code in my repo, if you don't allow me to do this, let me know, i will remove it.
Repo: [https://github.com/zths/RPG_Maker_MV_Code_Injector](https://github.com/zths/RPG_Maker_MV_Code_Injector)

Thanks.

**Comment by emerladCoder** [comment]
Feel free to use or take anything you need from the repo.

**Comment by zths** [comment]
Thank you.
