### ISSUE TITLE
The unpacker in readme is no longer useful for newest games

### ISSUE THREAD

**Issue by allape** [emerladCoder/RPG-Maker-MV-Cheat-Menu-Plugin#3]
Newest EnigmaVBUnpacker: [https://mega.nz/file/QhBSXSJL#BOjn1xsAxheWaphuhL9YhQQceOHiNfmjov05cBJJSsk](https://mega.nz/file/QhBSXSJL#BOjn1xsAxheWaphuhL9YhQQceOHiNfmjov05cBJJSsk)
found in [https://f95zone.to/threads/rpg-maker-mv-unpacker.417/post-3577739](https://f95zone.to/threads/rpg-maker-mv-unpacker.417/post-3577739)

**Comment by emerladCoder** [comment]
I have updated the readme to remove the invalid link, most games are no new games are no longer being packed so EnigmaVBUnpacker isn't needed in most cases.
