### ISSUE TITLE
add MZ Plugin Patcher

### ISSUE THREAD

**Issue by Wolf-ON** [emerladCoder/RPG-Maker-MV-Cheat-Menu-Plugin#4]
As I have checked, MV Cheat Menu Plugin works perfectly on RPG Maker MZ, It only needs bit modified MV Plugin Patcher (as it doesn't use www\js location but only js.

**Comment by star2056** [comment]
agreed, it would be great if it can use on MZ games.

**Comment by NamelessMagician** [comment]
#9 I have created a branch that fixes this, And pull requested it. But you can download the updated patcher from my fork

**Comment by emerladCoder** [comment]
Closed with merger of PR #9 thanks to @NamelessMagician
