### ISSUE TITLE
Darktoz games and the rpg maker.

### ISSUE THREAD

**Issue by saucefar** [emerladCoder/RPG-Maker-MV-Cheat-Menu-Plugin#6]
Since the patcher does not work for me i had to add the line manually but that did not work either even if i put it in with the other values or outside, up or down.

I noticed all the lines had a , so i added it like this {"name":"Cheat_Menu","status":true,"description":"","parameters":{}}, and it worked, installer does not tell you this.

**Comment by NamelessMagician** [comment]
If you add it manually at the beginning it will need a comma.
 If you add it at the end of the array, it does not need a comma, but you will need to add a comma to the one before it.

**Comment by emerladCoder** [comment]
That is correct, you will need the , before/after depending on where you insert the JavaScript Object in the $plugins array. 
I updated the readme to attempt to clarify.
